services:
  gpu-monitor:
    image: xxfantasiadownxx/gpu-monitor:latest
    ports:
      - "10101:10101"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
